#!/usr/bin/env python3
"""Make every skill self-contained for deliverable generation.

Each skill folder must work when it is loaded on its own — into a GrokBot
agent, a Claude project, a zip upload — so each one carries:

  scripts/ma_render.py     byte-identical copy of shared/ma_render/ma_render.py
  scripts/requirements.txt the python packages its scripts use
  SKILL.md                 a generated "Deliverable format" section (between
                           the ma-render markers) naming the file types it
                           delivers and the exact commands to build them
  metadata.deliverables    the same file types, machine-readable

The canonical engine and the per-skill profile table live here, so there is
one place to change. CI runs --check and fails on any drift.

    python3 scripts/sync_renderer.py            # write copies and sections
    python3 scripts/sync_renderer.py --check    # verify, change nothing
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ENGINE = REPO / "shared" / "ma_render" / "ma_render.py"
SKILLS = REPO / "skills"

BEGIN = "<!-- ma-render:begin — generated by scripts/sync_renderer.py; edit the template there -->"
END = "<!-- ma-render:end -->"

BASE_REQUIREMENTS = [
    "python-pptx>=1.0",
    "python-docx>=1.1",
    "matplotlib>=3.7",
    "reportlab>=4.0",
]

# Profiles decide the file types a skill hands over and the render command it
# shows. Default is "report" (Word + PDF). Markdown is never a deliverable.
PROFILES = {
    "report": {
        "deliverables": ["docx", "pdf"],
        "what": "a designed **Word document (.docx) plus a PDF copy**",
        "cmd": "report", "ext": "docx",
    },
    "report+deck": {
        "deliverables": ["docx", "pdf", "pptx"],
        "what": "a designed **Word document (.docx) plus a PDF copy**, and a "
                "**PowerPoint deck (.pptx)** when the audience will be presented to",
        "cmd": "report", "ext": "docx", "also_deck": True,
    },
    "deck": {
        "deliverables": ["pptx", "pdf"],
        "what": "a designed **PowerPoint deck (.pptx) plus a PDF copy**",
        "cmd": "deck", "ext": "pptx",
    },
    "figure": {
        "deliverables": ["png", "svg", "docx", "pptx", "pdf"],
        "what": "**PNG/SVG figures placed inside a .docx, .pptx or PDF** — a "
                "figure file on its own is an asset, not the deliverable",
        "cmd": "report", "ext": "docx", "also_deck": True,
    },
    "html": {
        "deliverables": ["html", "pdf", "docx"],
        "what": "a self-contained **interactive HTML report plus a PDF or Word "
                "companion** for readers who print, file or forward",
        "cmd": "report", "ext": "docx",
    },
    "xlsx": {
        "deliverables": ["xlsx", "docx", "pdf"],
        "what": "an **Excel workbook (.xlsx)** for the data and a **Word/PDF "
                "summary** for the reader",
        "cmd": "report", "ext": "docx",
    },
}

SKILL_PROFILE = {
    "medical-slide-deck": "deck",
    "congress-abstract-and-poster": "deck",
    "advisory-board-design": "report+deck",
    "executive-briefing": "report+deck",
    "congress-intelligence": "report+deck",
    "field-insight-synthesis": "report+deck",
    "medical-strategy-plan": "report+deck",
    "launch-medical-readiness": "report+deck",
    "integrated-evidence-plan": "report+deck",
    "strategic-analysis": "report+deck",
    "competitive-intelligence": "report+deck",
    "medical-education-program": "report+deck",
    "scientific-platform": "report+deck",
    "scientific-communication-strategy": "report+deck",
    "evidence-gap-analysis": "report+deck",
    "medical-affairs-metrics": "report+deck",
    "library-menu": "report+deck",
    "data-visualization-for-medical": "figure",
    "diagram-and-schema": "figure",
    "visual-abstract": "figure",
    "consulting-grade-design": "report+deck",
    "interactive-html-report": "html",
    "spreadsheet-analysis": "xlsx",
    "medical-affairs-orchestrator": "report+deck",
    "workshop-launcher": "report+deck",
}

# Skills with a specialised builder keep it; the section names it so the
# agent does not reach for the general engine where a stricter one exists.
SPECIALISED = {
    "medical-slide-deck": "`scripts/build_deck.py` wraps the engine and blocks a deck without "
                          "approval status or a data slide without its citation — use it for "
                          "medical decks.",
    "scientific-manuscript": "Journal manuscripts use `scripts/build_manuscript.py` (ICMJE, "
                             "GPP 2022 and reporting-guideline sections); use the engine for "
                             "cover letters, summaries and response-to-reviewer documents.",
    "medical-correspondence": "Letters use `scripts/letter.py`; use the engine for anything "
                              "longer than a letter.",
    "congress-abstract-and-poster": "Posters use `scripts/build_poster.py`; congress presentations "
                                    "and readouts use the engine.",
    "pdf-generation": "`scripts/build_pdf.py` remains for simple response documents; the engine "
                      "is preferred because it builds the Word file and the PDF from one spec.",
    "spreadsheet-analysis": "Workbooks use `scripts/sheets.py`; the written summary uses the engine.",
    "interactive-html-report": "The interactive page uses `scripts/build_report.py`.",
    "data-visualization-for-medical": "Single clinical figures (KM, forest, waterfall, AE) use "
                                      "`scripts/clinical_figures.py`; place them with an `image` "
                                      "block or slide.",
    "visual-abstract": "The abstract graphic uses `scripts/visual_abstract.py`.",
    "diagram-and-schema": "Diagrams use `scripts/diagram.py`.",
    "library-menu": "The menu card uses `scripts/menu_card.py`.",
}


def section_for(skill: str) -> str:
    prof = PROFILES[SKILL_PROFILE.get(skill, "report")]
    cmd, ext = prof["cmd"], prof["ext"]
    lines = [
        BEGIN,
        "## Deliverable format",
        "",
        f"Deliver {prof['what']}.",
        "Build it with this skill's bundled engine. Markdown is for drafting only —",
        "never hand over a .md file, and never hand-write a python-pptx or",
        "python-docx script instead of the engine.",
        "",
        "```bash",
        "python3 scripts/ma_render.py bootstrap      # installs python-pptx, python-docx, matplotlib, reportlab",
        f"python3 scripts/ma_render.py example {cmd} > spec.json   # spec format; or write a markdown draft",
        f"python3 scripts/ma_render.py {cmd} spec.json --out outputs/<name>.{ext} --preview outputs/preview",
    ]
    if prof.get("also_deck"):
        lines.append("python3 scripts/ma_render.py deck deck.json --out outputs/<name>.pptx --preview outputs/preview")
    lines += [
        "```",
        "",
        "Turn numbers into `stats`/`chart` blocks and comparisons into tables or",
        "`two_column` slides; put a source on every data element. Then open",
        "`outputs/preview/contact-sheet.png`, fix every overflow, empty or text-only",
        "page, and re-render. If a package cannot be installed the engine still",
        "writes a real .docx or print-ready HTML and says what degraded.",
    ]
    if skill in SPECIALISED:
        lines += ["", SPECIALISED[skill]]
    lines.append(END)
    return "\n".join(lines)


def insert_section(text: str, section: str) -> str:
    if BEGIN.split(" — ")[0] in text:
        pattern = re.compile(re.escape(BEGIN.split(" — ")[0]) + r".*?" + re.escape(END), re.S)
        return pattern.sub(lambda _m: section, text, count=1)
    # Place before "Before you finish" / "References" when present, else at the end.
    m = re.search(r"^## (Before you finish|References)\b", text, re.M)
    if m:
        return text[: m.start()] + section + "\n\n" + text[m.start():]
    return text.rstrip("\n") + "\n\n" + section + "\n"


def set_deliverables(text: str, deliverables: list[str]) -> str:
    fm_end = text.index("\n---", 3)
    fm, rest = text[:fm_end], text[fm_end:]
    value = "[" + ", ".join(deliverables) + "]"
    if re.search(r"^  deliverables:.*$", fm, re.M):
        fm = re.sub(r"^  deliverables:.*$", f"  deliverables: {value}", fm, flags=re.M)
    elif re.search(r"^  produces:.*$", fm, re.M):
        fm = re.sub(r"^(  produces:.*)$", lambda m: m.group(1) + f"\n  deliverables: {value}", fm,
                    count=1, flags=re.M)
    else:
        fm = re.sub(r"^(metadata:)$", lambda m: m.group(1) + f"\n  deliverables: {value}", fm,
                    count=1, flags=re.M)
    return fm + rest


def requirements_for(skill_dir: Path, text: str) -> str:
    reqs = list(BASE_REQUIREMENTS)
    m = re.search(r"^  python:\s*\[(.*)\]\s*$", text, re.M)
    if m:
        for pkg in [p.strip().strip("'\"") for p in m.group(1).split(",") if p.strip()]:
            name = re.split(r"[<>=!~ ]", pkg)[0].lower()
            if not any(re.split(r"[<>=!~ ]", r)[0].lower() == name for r in reqs):
                reqs.append(pkg)
    return ("# Python packages this skill's scripts use. Generated by scripts/sync_renderer.py.\n"
            "# Install with:  python3 scripts/ma_render.py bootstrap   (or pip install -r this file)\n"
            + "\n".join(reqs) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify only; exit 1 on drift")
    args = ap.parse_args()

    engine = ENGINE.read_bytes()
    drift: list[str] = []
    skills = sorted(p for p in SKILLS.iterdir() if (p / "SKILL.md").exists())
    unknown = set(SKILL_PROFILE) - {p.name for p in skills}
    if unknown:
        drift.append(f"profile table names unknown skills: {sorted(unknown)}")

    for skill_dir in skills:
        name = skill_dir.name
        skill_md = skill_dir / "SKILL.md"
        text = skill_md.read_text(encoding="utf-8")
        new_text = set_deliverables(insert_section(text, section_for(name)),
                                    PROFILES[SKILL_PROFILE.get(name, "report")]["deliverables"])
        copy = skill_dir / "scripts" / "ma_render.py"
        reqs = skill_dir / "scripts" / "requirements.txt"
        new_reqs = requirements_for(skill_dir, new_text)

        if args.check:
            if not copy.exists() or copy.read_bytes() != engine:
                drift.append(f"skills/{name}/scripts/ma_render.py differs from shared/ma_render/ma_render.py")
            if new_text != text:
                drift.append(f"skills/{name}/SKILL.md deliverable section or metadata is stale")
            if not reqs.exists() or reqs.read_text(encoding="utf-8") != new_reqs:
                drift.append(f"skills/{name}/scripts/requirements.txt is stale")
            continue

        copy.parent.mkdir(parents=True, exist_ok=True)
        copy.write_bytes(engine)
        copy.chmod(0o755)
        reqs.write_text(new_reqs, encoding="utf-8")
        if new_text != text:
            skill_md.write_text(new_text, encoding="utf-8")

    if args.check:
        for d in drift:
            print(f"  DRIFT  {d}")
        if drift:
            print(f"\n{len(drift)} problem(s). Run: python3 scripts/sync_renderer.py")
            return 1
        print(f"All {len(skills)} skills carry the current engine, requirements and deliverable section.")
        return 0
    print(f"Synced the engine into {len(skills)} skills.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
